title: <p align="center"> Rohan Mehta </p>

logo: "/images/rohan_image.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/rohan-mehta-89a2a785/">LinkedIn</a> |
  <a href="https://github.com/rmehta678">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently pursing a Masters in Engineering at the UCLA Samueli School of Engineering
  <br><br>
  I am currently an Artificial Intelligence Systems Engineer at the Northrop Grumman AI&A (Artificial Intelligence & Analytics) Department
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
